import Head from 'next/head';
import Image from 'next/image';
import { Caladea, Inter } from '@next/font/google';
import Header from '@/components/Header';
import { useState } from 'react';
import Hero from '@/components/Hero';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [popup, setPopup] = useState();

  const togglePopupNav = () => {
    return setPopup(!popup);
  };
  console.log(popup);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100">
        <Header togglePopupNav={togglePopupNav} />

        {/* Popup nav */}

        {/* Hero */}
        <Hero />
        {/* features */}

        {/* faq */}
      </main>

      {/* footer */}
    </>
  );
}
